version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - admin_db

  main_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: main
      #MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33061:3306
